// Generated by CoffeeScript 1.9.3
var glow, makeStatic, write;

glow = function($model, $target) {
  var offset;
  offset = $target.offset();
  return $model.addClass('glow').css({
    top: offset.top,
    left: "calc(" + offset.left + "px - 20vh)"
  });
};

write = function($obj, text, glowFn, done) {
  var t;
  if (text.length > 0) {
    t = (function() {
      switch (text[0]) {
        case "#":
          return "<br/>";
        case "*":
          return t = "<strong>ER</Strong>";
        case '|':
          glowFn();
          return t = '';
        default:
          return text[0];
      }
    })();
    $obj.append(t);
    return setTimeout((function() {
      return write($obj, text.slice(1), glowFn, done);
    }), (Math.random() + 2) * 28);
  } else {
    $obj.addClass("writer-done");
    return setTimeout(done, 2000);
  }
};

makeStatic = function($obj) {
  return $obj.height($obj.height()).width($obj.width());
};
