// Generated by CoffeeScript 1.9.3
var setupPart2;

setupPart2 = function(sWidth, sHeight) {
  var done1, done2, glowFn1, glowFn2, glowFn3, isNight;
  glowFn1 = function() {
    return glow($('#lightbulb'), $('#writer-1'));
  };
  glowFn2 = function() {
    return glow($('#screen'), $('#writer-2'));
  };
  glowFn3 = function() {
    return glow($('#smiley'), $('#writer-3'));
  };
  $('.background-filter').addClass('night');
  isNight = true;
  $("#no-press h1 span").css("color", "transparent");
  $("#no-press h1").delay(600).queue(function() {
    return makeStatic($(this)).html("").dequeue();
  }).animate({
    padding: 0,
    width: 0
  }, 600).queue(function() {
    return $(this).remove();
  });
  $(".text").css("height", sHeight * .6);
  done2 = function() {
    return write($("#writer-3"), text3, glowFn3, function() {
      return $(".writer").css("color", "#94FFFC");
    });
  };
  done1 = function() {
    return write($("#writer-2"), text2, glowFn2, done2);
  };
  return setTimeout((function() {
    return write($("#writer-1"), text1, glowFn1, done1);
  }), 3000);
};
